BREAKING CHANGE: Restrict which schemas can be used with the typesystem.
thenativeweb/get-graphql-from-jsonschema pull request #293
Opened 2021-05-07 09:28 UTC by dotKuro

2021-05-07 12:48 UTC, yeldiRium requested changes

2021-05-07 12:48 UTC, yeldiRium commented on README.md
> +- The `patternProperties`, `maxProperties`, `minProperties`, `dependencies` and `propertyNames` field are not allowed. The `additionalProperties` field must be set to `false` because GraphQl demands
```suggestion
- The `patternProperties`, `maxProperties`, `minProperties`, `dependencies` and `propertyNames` fields are not allowed. The `additionalProperties` field must be set to `false` because GraphQl demands precisely defined types.
```

2021-05-07 12:48 UTC, yeldiRium commented on README.md
> +The `oneOf` and `anyOf` keywords are supported with a limitation on their usage: There must be no other properties on the same level as the either of them.
```suggestion
The `oneOf` and `anyOf` keywords are supported with a limitation on their usage: There must be no other properties on the same level as either of them.
```

2021-05-07 12:48 UTC, yeldiRium commented on README.md
> +unsupported parts of json-schema can lead to silent misbehaviour ins javascript.
```suggestion
unsupported parts of json-schema can lead to silent misbehaviour in javascript. 
```

2021-05-12 06:52 UTC, goloroden approved these changes

2021-05-12 06:54 UTC, merged